### ISSUE TITLE
[meta, github] publish your hg-fast-export rules

### ISSUE THREAD

**Issue by imz** [mhorbul/libpst#2]
Hi,

I've recently been working with some issues in ALT's libpst package, whereby I've been communicating with Carl Byington who maintains the upstream project in mercurial.

Since ALT's build system takes input in Git, I've started converting from Hg to Git in order to get fresh patches (and build packages).

I've discovered your github repo where you seem to do the same conversion. Several days ago, my result of conversion https://github.com/imz/libpst had a "merge-base" with yours. (Mine is reproducible with consecutive runs of `hg-fast-export -r ../libpst/` from ) The divergence was at a commit where my converter has put `carl <carl@five-ten-sg.com>` as the committer whereas yours has put `carl@five-ten-sg.com <carl@five-ten-sg.com>` (less human-friendly).

But now!.. Then you updated the conversion completely a few days ago, and the common merge-base is gone.

I don't want to have two different conversions on github, but since I'm going to run my conversion on my own, I'd like to know how to reproduce your results. So that we don't diverge.

Mine `hg-fast-export` is from a snapshot:

```
* Чт май 29 2014 Eugeny A. Rostovtsev (REAL) <real at altlinux.org> 0.1-alt9
- New snapshot (ALT #30005)

```

**Comment by mhorbul** [comment]
I have been using this lib long time ago. I do not need it anymore. I updated it as you someone reported an issue and you responded back. I realized that my repo is too old and updated it right away. If you are going to keep up-to-date git version on github I will be happy to remove my repo and leave a reference to yours.

**Comment by imz** [comment]
On Mon, 5 Sep 2016, Maksim Horbul wrote:

> I have been using this lib long time ago. I do not need it anymore. I updated it as you someone reported an issue and you responded back. I realized that my repo is too old and updated it right away. If you are going to keep up-to-date git version on github I will
> be happy to remove my repo and leave a reference to yours.

I think it is OK if we both keep it on github, and update from time to 
time.

But I worry about the version of `hg-fast-export` and its options which 
each of us is using when doing the updates. Let's open this information, 
so that our results become compatible.

Your last update diverged even further from what I get than your previous 
history.

Now I run the v160415 revision of <repo.or.cz/fast-export.git> or 
https://github.com/frej/fast-export (commit 
c614ae776bd023095c91b849f4da268429b79455) like this:

hg-fast-export -r ../libpst

We diverge even in the initial commit (before you updated, we had 
identical initial commits in our independent conversions) -- copied from 
gitk and hgk:

Original hg commit:

```
 Changeset: 0
 Branch: default
 User: carl
 Date: Fri Jul 09 18:26:16 MSD 2004
 Tags: libpst_0_5

     Initial revision
```

My (and your older) initial git commit:

```
 Author: carl <devnull@localhost>  2004-07-09 18:26:16
 Committer: carl <devnull@localhost>  2004-07-09 18:26:16
 Tags: libpst_0_5
 Branches: 160415/debian, 160415/hg, debian, old-hg, remotes/scintill@github/master, upstream/debian, upstream/hg
 Follows:

     Initial revision
```

Your new git commit:

```
 Author: carl <unknown>  2004-07-09 18:26:16
 Committer: carl <unknown>  2004-07-09 18:26:16
 Branch: remotes/mhorbul@github/master
 Follows:

    Initial revision
```

The problem is the diverging Author/Committer email when it is absent.

Which version of hg-fast-export do you use?

Let's use the same one! Let's decide which one to use.
